# Generated by Django 4.2.5 on 2024-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloAfricaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('useremail', models.EmailField(max_length=254)),
                ('telnumber', models.CharField(max_length=16)),
                ('destination', models.CharField(max_length=50)),
                ('howMany', models.IntegerField()),
                ('arrivals', models.DateTimeField()),
                ('bookmessage', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
